# Chang Hyun Lee
# the yaml file for the launch file of attack_module

# sensor_attack_type includes
# 1. zero_lat_long : zero-out the coordinate values of the GPS
# 2. similar_values : insert values that resemble to a set of normal values of GPS
# 	- because the GPS values are within range in this case, you increment/decrement normal data by larger values
# 		- in general,
# 		- latitude is within a range of 44.9990xxxxx and 45.000xxxxx
#		- longitude is within a range of -81.00xxxxx and -80.99xxxxx
#		- can change the values by adding/substracting value specified by anomaly_data_range
#	

publish_rate : 5
outlier_queue_size: 100
sensor_attack_type : "similar_values"
similar_values_attack:
	normal_lat_min_value : 44.999
	normal_lat_max_value : 45.000
	normal_long_min_value : -81.00
	normal_long_max_value : -80.99
	anomaly_data_range : 5


